# galaxy theme

background  #1c2836
foreground  #ffffff

cursor                #bbbbbb

selection_foreground  #1c2836
selection_background  #b4d5ff

color0  #000000
color8  #545454

# red
color1                #f9555f
# light red
color9                #fa8b8e

# green
color2                #20af89
# light green
color10               #34bb99

# yellow
color3                #fdf029
# light yellow
color11               #ffff55

# blue
color4                #589cf5
# light blue
color12               #589cf5

# magenta
color5                #934d95
# light magenta
color13               #e75598

# cyan
color6                #1e9ee6
# lighy cyan
color14               #3978bb

# light gray
color7                #bbbbbb
# dark gray
color15               #ffffff
